### ISSUE TITLE
Using findFirst with include returns all users not just connected

### ISSUE THREAD

**Issue by ilkkanisula** [morintd/prismock#366]
When calling findFirst entry with include users connected prismock returns all users instead of connected.

Here is example code:
```javascript
await prisma.entry.create({
        group: { connect: { id: 1 } },
        members: { connect: [{id: 1}, {id: 2}] }
})

await prisma.entry.findFirst({
        where: {
            id: Number(uid),
            group: { id: Number(id) },
        },
        include: { members: true })
```

Above query **incorrectly returns full list of users** and not just ones that are connected to entry. Same doesn't happen when using production prisma with PostgreSQL backend.

Schema:
```javascript
model Group {
  id        Int        @id @default(autoincrement())
  members   User[]
  entries Entry[]
}

model User {
  id         Int        @id @default(autoincrement())
  email      String     @unique
  groups      Group[]
}


model Entry {
  id        Int      @id @default(autoincrement())
  members   User[]
  group      Group     @relation(fields: [groupId], references: [id])
  groupId    Int
}
```

**Comment by morintd** [comment]
Hello @ilkkanisula , I've been unable to reproduce this issue.

Please provide a minimal repo where your issue is happening and I'll definitely use it to solve it

**Comment by morintd** [comment]
Thanks a lot, I'll have a look now

**Comment by morintd** [comment]
Should be fixed in https://github.com/morintd/prismock/pull/370

**Comment by ilkkanisula** [comment]
Great work. Confirmed this works on above example repo also when using 1.13.1 version.

FYI: For more complex scenario with my real application this did not fix the behaviour for some reason. I still get full list of group members using findfirst + include. Did not manage to produce this with the above simple repo. I'll report back if I figure out what is the difference. See failing query below.

```javascript
prisma.group.findFirst({
        where: { id: groupId },
        include: {
            members: true,
            entry: { include: { members: true } }
        }
    })
```
